# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74eb3309aa952425ff15050c3ddd2925469016417dc371a669add162109d5e9acf97bff5081800abb70bc880e264c13713a689bde295f16dcd2dbd898d6d2ccb

test:
  secret_key_base: c9f5f1e479b3c84f3ef5413a844eacdef031d37907bb56413d0d1d5637dbc1c6aa7bf06dc9b37aeed20138c3987ca5ca5912bf127954257458c7380ff0f93678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
